FROM elixir:1.15-slim

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential git curl nodejs npm python3 && \
    npm install -g npm@latest webpack webpack-cli && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install hex package manager and Phoenix framework
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force

# Set iex history
ENV ERL_AFLAGS="-kernel shell_history enabled"

# Copy entrypoint script
COPY docker-entrypoint.dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.dev.sh

ENTRYPOINT ["docker-entrypoint.dev.sh"]
CMD ["mix", "phx.server"]
