FROM elixir:1.15-alpine

# Install build dependencies
RUN apk add --no-cache build-base git nodejs npm python3 && \
    npm install -g npm@latest webpack webpack-cli

WORKDIR /app

# Install hex package manager and Phoenix framework
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force

# Set iex history
ENV ERL_AFLAGS="-kernel shell_history enabled"

# Copy entrypoint script
COPY docker-entrypoint.dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.dev.sh

ENTRYPOINT ["docker-entrypoint.dev.sh"]
CMD ["mix", "phx.server"]
